/**
 * ============================================================================
 *  Montgomery County, PA -- individual property sale records (real, sourced).
 * ============================================================================
 *
 * Unlike the single `medianPrice` figure per town in `localMarket.ts` (a
 * commercial estimate, hand-transcribed from Zillow/Redfin), these are actual
 * transactions pulled straight from the county's own assessment database --
 * one row per sale, with the address, price, date and (where recorded) beds,
 * baths and square footage.
 *
 * Source: Montgomery County Parcels, Montgomery County GIS
 *   https://www.montgomerycountypa.gov/departments/board-assessment-appeals/property-data-data-requests
 *   Live feature service (free, no key, updated monthly from the assessment
 *   database):
 *   https://services1.arcgis.com/kOChldNuKsox8qZD/arcgis/rest/services/Montgomery_County_Parcels/FeatureServer/6
 * Retrieved: 2026-08-15
 * Refresh: monthly (county publishes a new snapshot on a published schedule --
 *   see the service's own description for the current month's date).
 *
 * ---------------------------------------------------------------------------
 *  READ THIS BEFORE TREATING THE AGGREGATE AS A MEDIAN
 * ---------------------------------------------------------------------------
 *
 * Generated by `scripts/fetch-montco-sales.mjs` (last 12 months, > $50,000,
 * residential only, capped at 5 most-recent complete records per
 * municipality), then reviewed by hand -- a handful of records with
 * non-residential-looking addresses (PO boxes, a corporate center, a
 * suite number on an implausibly high-priced record) were dropped, which is
 * why a few municipalities below have fewer than 5. Do NOT treat `medianOf()`
 * below as a real median sale price -- it is a range across whatever sales
 * happened to be pulled and kept, useful for a rough sense of what a town's
 * housing stock looks like, not a market snapshot.
 *
 * County sale records also include non-arm's-length transfers (family
 * transfers, deed corrections, sheriff sales) that can carry unrealistic
 * prices. Every record here has already been filtered to CONSIDERAT > $50,000
 * and to residential parcels with recorded beds/baths/sqft, plus the manual
 * pass above, but that is not a substitute for a real filter on transfer
 * type.
 *
 * ---------------------------------------------------------------------------
 *  STALENESS
 * ---------------------------------------------------------------------------
 *
 * Per docs/adr/0001-stale-data-threshold.md, a home sale older than 1 year is
 * stale and not trustworthy as a market signal. Because this sample was
 * pulled with a 12-month window in the first place, essentially everything
 * below is fresh as of the retrieval date above -- that will stop being true
 * the longer this file goes without a re-fetch. `salesIn()` returns every
 * record on file (unfiltered, for audit purposes); `freshSalesIn()` is what
 * the UI and any aggregate should use instead, since it drops anything past
 * the threshold.
 */

import { isStale } from './freshness';

export interface RecentSale {
  /**
  Matches `Municipality.name` in `localMarket.ts` (Montgomery County only, so far).
  */
  municipality: string;
  address: string;
  /**
  ISO date the deed was recorded, YYYY-MM-DD.
  */
  saleDate: string;
  /**
  The deed's stated consideration -- what the county recorded as the price.
  */
  salePrice: number;
  yearBuilt?: number;
  beds?: number;
  baths?: number;
  halfBaths?: number;
  sqft?: number;
}

export const RECENT_SALES: RecentSale[] = [
  // --- Abington ------------------------------------------------------------------
  { municipality: 'Abington', address: '821 Beverly Rd', saleDate: '2026-07-09', salePrice: 730000, yearBuilt: 1952, beds: 5, baths: 3, sqft: 2745 },
  { municipality: 'Abington', address: '337 Edge Hill Rd', saleDate: '2026-07-07', salePrice: 300000, yearBuilt: 1925, beds: 3, baths: 2, sqft: 1442 },
  { municipality: 'Abington', address: '1910 Maplewood Ave', saleDate: '2026-07-06', salePrice: 495000, yearBuilt: 1950, beds: 3, baths: 1, halfBaths: 1, sqft: 1370 },
  { municipality: 'Abington', address: '100 Banbury Ave', saleDate: '2026-07-06', salePrice: 314083, yearBuilt: 1989, beds: 3, baths: 2, halfBaths: 1, sqft: 2072 },
  { municipality: 'Abington', address: '343 Wyndmoor Ln', saleDate: '2026-07-02', salePrice: 1000000, yearBuilt: 1986, beds: 5, baths: 4, halfBaths: 1, sqft: 5502 },
  // --- Ambler --------------------------------------------------------------------
  { municipality: 'Ambler', address: '115 S Chestnut St', saleDate: '2026-06-26', salePrice: 319900, yearBuilt: 1900, beds: 2, baths: 1, sqft: 1332 },
  { municipality: 'Ambler', address: '41 N Spring Garden St', saleDate: '2026-06-24', salePrice: 430000, yearBuilt: 1900, beds: 2, baths: 1, halfBaths: 1, sqft: 1241 },
  { municipality: 'Ambler', address: '136 Greenwood Ave', saleDate: '2026-06-18', salePrice: 625000, yearBuilt: 1890, beds: 3, baths: 2, halfBaths: 1, sqft: 1411 },
  { municipality: 'Ambler', address: '113 S Chestnut St', saleDate: '2026-06-17', salePrice: 289900, yearBuilt: 1900, beds: 2, baths: 1, sqft: 1390 },
  { municipality: 'Ambler', address: '117 Mary Ambler Way', saleDate: '2026-06-10', salePrice: 650000, yearBuilt: 2010, beds: 3, baths: 2, halfBaths: 2, sqft: 2452 },
  // --- Bridgeport ----------------------------------------------------------------
  { municipality: 'Bridgeport', address: '545 Grove St', saleDate: '2026-07-01', salePrice: 430000, yearBuilt: 2011, beds: 3, baths: 3, halfBaths: 1, sqft: 2022 },
  { municipality: 'Bridgeport', address: '203 W Eighth St', saleDate: '2026-06-29', salePrice: 580000, yearBuilt: 2026, beds: 3, baths: 2, halfBaths: 1, sqft: 1726 },
  { municipality: 'Bridgeport', address: '65 E Front St', saleDate: '2026-06-24', salePrice: 545000, yearBuilt: 2025, beds: 3, baths: 2, halfBaths: 3, sqft: 2060 },
  { municipality: 'Bridgeport', address: '306 Prospect Ave', saleDate: '2026-06-23', salePrice: 432500, yearBuilt: 1900, beds: 4, baths: 2, halfBaths: 1, sqft: 1920 },
  { municipality: 'Bridgeport', address: '4432 E Bristol Rd Ste 4b', saleDate: '2026-06-22', salePrice: 160000, yearBuilt: 1900, beds: 3, baths: 1, halfBaths: 1, sqft: 1790 },
  // --- Bryn Athyn ----------------------------------------------------------------
  { municipality: 'Bryn Athyn', address: '3001 Marlin Rd', saleDate: '2026-01-12', salePrice: 915000, yearBuilt: 1971, beds: 2, baths: 2, halfBaths: 1, sqft: 1840 },
  { municipality: 'Bryn Athyn', address: '664 Dale Rd', saleDate: '2025-11-25', salePrice: 750000, yearBuilt: 1957, beds: 5, baths: 2, sqft: 2356 },
  { municipality: 'Bryn Athyn', address: '2666 Alnwick Rd', saleDate: '2025-10-28', salePrice: 845000, yearBuilt: 1940, beds: 5, baths: 3, halfBaths: 1, sqft: 2749 },
  // --- Cheltenham ----------------------------------------------------------------
  { municipality: 'Cheltenham', address: '492 Red Oak Dr', saleDate: '2026-07-08', salePrice: 490000, yearBuilt: 1999, beds: 2, baths: 3, halfBaths: 1, sqft: 3665 },
  { municipality: 'Cheltenham', address: '552 Custis Rd', saleDate: '2026-07-06', salePrice: 715000, yearBuilt: 1940, beds: 3, baths: 2, halfBaths: 1, sqft: 1816 },
  { municipality: 'Cheltenham', address: '320 Maple Ave', saleDate: '2026-07-02', salePrice: 600000, yearBuilt: 1995, beds: 4, baths: 2, halfBaths: 1, sqft: 2340 },
  { municipality: 'Cheltenham', address: '151 Greenwood Ave', saleDate: '2026-07-01', salePrice: 350000, yearBuilt: 1895, beds: 4, baths: 1, sqft: 1758 },
  { municipality: 'Cheltenham', address: '1405 W Church Rd', saleDate: '2026-06-30', salePrice: 565000, yearBuilt: 1950, beds: 5, baths: 2, halfBaths: 1, sqft: 2968 },
  // --- Collegeville --------------------------------------------------------------
  { municipality: 'Collegeville', address: '353 Colonial Ave', saleDate: '2026-07-09', salePrice: 659000, yearBuilt: 1969, beds: 4, baths: 3, sqft: 2959 },
  { municipality: 'Collegeville', address: '1125 Kingsley Hall Dr', saleDate: '2026-07-06', salePrice: 384805, yearBuilt: 1983, beds: 3, baths: 1, halfBaths: 1, sqft: 1830 },
  { municipality: 'Collegeville', address: '492 Shakespeare Dr', saleDate: '2026-06-22', salePrice: 775000, yearBuilt: 1994, beds: 4, baths: 2, halfBaths: 1, sqft: 2904 },
  { municipality: 'Collegeville', address: '220 Richard Way', saleDate: '2026-06-10', salePrice: 967500, yearBuilt: 1994, beds: 4, baths: 4, halfBaths: 1, sqft: 3269 },
  { municipality: 'Collegeville', address: '36 E First Ave', saleDate: '2026-05-26', salePrice: 357000, yearBuilt: 1910, beds: 3, baths: 1, sqft: 1298 },
  // --- Conshohocken --------------------------------------------------------------
  { municipality: 'Conshohocken', address: '627 Spring Mill Ave', saleDate: '2026-07-05', salePrice: 410000, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1077 },
  { municipality: 'Conshohocken', address: '239 E Twelfth Ave', saleDate: '2026-06-26', salePrice: 500900, yearBuilt: 1950, beds: 3, baths: 1, halfBaths: 1, sqft: 1280 },
  { municipality: 'Conshohocken', address: '411 W Tenth Ave', saleDate: '2026-06-25', salePrice: 521000, yearBuilt: 1925, beds: 3, baths: 1, halfBaths: 1, sqft: 1280 },
  { municipality: 'Conshohocken', address: '332 Spring Mill Ave', saleDate: '2026-06-24', salePrice: 481000, yearBuilt: 1874, beds: 4, baths: 1, sqft: 1868 },
  { municipality: 'Conshohocken', address: '132 E Third Ave', saleDate: '2026-06-22', salePrice: 369000, yearBuilt: 1874, beds: 4, baths: 1, sqft: 1358 },
  // --- Douglass ------------------------------------------------------------------
  { municipality: 'Douglass', address: '194 Congo Rd', saleDate: '2026-07-06', salePrice: 590000, yearBuilt: 1952, beds: 3, baths: 1, halfBaths: 1, sqft: 2246 },
  { municipality: 'Douglass', address: '54 Douglass St', saleDate: '2026-06-30', salePrice: 375000, yearBuilt: 1956, beds: 2, baths: 2, sqft: 2588 },
  { municipality: 'Douglass', address: '41 Estate Rd', saleDate: '2026-06-24', salePrice: 575900, yearBuilt: 1977, beds: 5, baths: 2, halfBaths: 1, sqft: 2768 },
  { municipality: 'Douglass', address: '922 Camp Rd', saleDate: '2026-06-23', salePrice: 475000, yearBuilt: 1951, beds: 3, baths: 2, sqft: 1726 },
  { municipality: 'Douglass', address: '35 Westbury Dr', saleDate: '2026-06-22', salePrice: 482000, yearBuilt: 2010, beds: 3, baths: 2, halfBaths: 1, sqft: 1572 },
  // --- East Greenville -----------------------------------------------------------
  { municipality: 'East Greenville', address: '1356 Michael Way', saleDate: '2026-06-22', salePrice: 432500, yearBuilt: 1960, beds: 2, baths: 1, halfBaths: 1, sqft: 1564 },
  { municipality: 'East Greenville', address: '711 Hamilton Rd', saleDate: '2026-06-16', salePrice: 325000, yearBuilt: 1974, beds: 4, baths: 2, halfBaths: 1, sqft: 1756 },
  { municipality: 'East Greenville', address: '431 Main St', saleDate: '2026-06-04', salePrice: 335000, yearBuilt: 1875, beds: 2, baths: 2, sqft: 1344 },
  { municipality: 'East Greenville', address: '146 Main St', saleDate: '2026-06-03', salePrice: 475000, yearBuilt: 1890, beds: 4, baths: 3, sqft: 2812 },
  { municipality: 'East Greenville', address: '224 Prince William Way', saleDate: '2026-05-29', salePrice: 250000, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1271 },
  // --- East Norriton -------------------------------------------------------------
  { municipality: 'East Norriton', address: '1566 Evangelina Ln', saleDate: '2026-07-08', salePrice: 435000, yearBuilt: 1939, beds: 3, baths: 1, sqft: 1608 },
  { municipality: 'East Norriton', address: '2615 Dogwood Ln', saleDate: '2026-07-06', salePrice: 442500, yearBuilt: 1952, beds: 4, baths: 2, sqft: 2354 },
  { municipality: 'East Norriton', address: '2915 Toll Gate Dr', saleDate: '2026-07-02', salePrice: 385000, yearBuilt: 1971, beds: 3, baths: 2, halfBaths: 1, sqft: 2153 },
  { municipality: 'East Norriton', address: '2 Patterson Ave Unit 2', saleDate: '2026-07-02', salePrice: 309000, yearBuilt: 1999, beds: 2, baths: 2, sqft: 1060 },
  { municipality: 'East Norriton', address: '218 Stony Way', saleDate: '2026-06-30', salePrice: 287500, yearBuilt: 1971, beds: 3, baths: 2, sqft: 1404 },
  // --- Franconia -----------------------------------------------------------------
  { municipality: 'Franconia', address: '101 Quince Dr', saleDate: '2026-07-01', salePrice: 391000, yearBuilt: 1992, beds: 3, baths: 1, halfBaths: 1, sqft: 1520 },
  { municipality: 'Franconia', address: '300 Westminster Ln', saleDate: '2026-06-30', salePrice: 545000, yearBuilt: 2001, beds: 2, baths: 2, sqft: 1874 },
  { municipality: 'Franconia', address: '327 Melbourne Way', saleDate: '2026-06-30', salePrice: 520000, yearBuilt: 2006, beds: 2, baths: 2, sqft: 2168 },
  { municipality: 'Franconia', address: '518 Berkshire Dr', saleDate: '2026-06-30', salePrice: 450000, yearBuilt: 1998, beds: 3, baths: 1, halfBaths: 1, sqft: 1632 },
  { municipality: 'Franconia', address: '182 Lions Gate Cir', saleDate: '2026-06-25', salePrice: 530000, yearBuilt: 1998, beds: 2, baths: 2, halfBaths: 1, sqft: 1733 },
  // --- Green Lane ----------------------------------------------------------------
  { municipality: 'Green Lane', address: '115 Green St', saleDate: '2026-05-12', salePrice: 350000, yearBuilt: 1960, beds: 2, baths: 1, sqft: 837 },
  { municipality: 'Green Lane', address: '429 Main St', saleDate: '2026-04-28', salePrice: 400000, yearBuilt: 1900, beds: 2, baths: 1, sqft: 1638 },
  { municipality: 'Green Lane', address: '116 Green St', saleDate: '2026-02-10', salePrice: 445000, yearBuilt: 1957, beds: 3, baths: 2, sqft: 1864 },
  { municipality: 'Green Lane', address: '5909 Lexington Dr', saleDate: '2025-12-19', salePrice: 436000, yearBuilt: 1951, beds: 3, baths: 2, sqft: 1260 },
  { municipality: 'Green Lane', address: '2380 Finland Rd', saleDate: '2025-11-04', salePrice: 210000, yearBuilt: 1935, beds: 2, baths: 1, halfBaths: 1, sqft: 1328 },
  // --- Hatboro -------------------------------------------------------------------
  { municipality: 'Hatboro', address: '3620 Reiniger Rd', saleDate: '2026-07-09', salePrice: 240000, yearBuilt: 1951, beds: 2, baths: 1, sqft: 957 },
  { municipality: 'Hatboro', address: '213 Green Lane Ter', saleDate: '2026-07-01', salePrice: 400000, yearBuilt: 1940, beds: 3, baths: 2, sqft: 1565 },
  { municipality: 'Hatboro', address: '221 E Montgomery Ave', saleDate: '2026-06-30', salePrice: 435000, yearBuilt: 1920, beds: 2, baths: 1, sqft: 1456 },
  { municipality: 'Hatboro', address: '367 Windsor Ave', saleDate: '2026-06-23', salePrice: 405000, yearBuilt: 1945, beds: 3, baths: 1, sqft: 930 },
  { municipality: 'Hatboro', address: '290 Yards Ct', saleDate: '2026-06-18', salePrice: 345000, yearBuilt: 2022, beds: 2, baths: 2, halfBaths: 1, sqft: 988 },
  // --- Hatfield Borough ----------------------------------------------------------
  { municipality: 'Hatfield Borough', address: '256 Larkspur Ln', saleDate: '2026-05-29', salePrice: 497000, yearBuilt: 2001, beds: 3, baths: 2, halfBaths: 1, sqft: 2064 },
  { municipality: 'Hatfield Borough', address: '390 Allentown Rd', saleDate: '2026-05-27', salePrice: 305000, yearBuilt: 1880, beds: 2, baths: 1, sqft: 1496 },
  { municipality: 'Hatfield Borough', address: '111 Raintree Crossing', saleDate: '2026-04-30', salePrice: 450000, yearBuilt: 2001, beds: 3, baths: 2, halfBaths: 1, sqft: 1968 },
  { municipality: 'Hatfield Borough', address: '369 Wheatfield Cir', saleDate: '2026-04-15', salePrice: 440000, yearBuilt: 2002, beds: 3, baths: 2, halfBaths: 1, sqft: 2262 },
  { municipality: 'Hatfield Borough', address: '36 N Maple Ave', saleDate: '2026-03-31', salePrice: 395000, yearBuilt: 1935, beds: 4, baths: 1, sqft: 1624 },
  // --- Hatfield Township ---------------------------------------------------------
  { municipality: 'Hatfield Township', address: '17 Derstine Rd', saleDate: '2026-07-01', salePrice: 555000, yearBuilt: 1963, beds: 3, baths: 2, halfBaths: 1, sqft: 1832 },
  { municipality: 'Hatfield Township', address: '2748 Valley Woods Rd', saleDate: '2026-06-29', salePrice: 555000, yearBuilt: 1980, beds: 3, baths: 1, halfBaths: 1, sqft: 1859 },
  { municipality: 'Hatfield Township', address: '1965 Foster Rd', saleDate: '2026-06-26', salePrice: 700000, yearBuilt: 1975, beds: 5, baths: 3, halfBaths: 1, sqft: 2916 },
  { municipality: 'Hatfield Township', address: '556 Grapevine Dr', saleDate: '2026-06-25', salePrice: 645000, yearBuilt: 1973, beds: 4, baths: 1, halfBaths: 2, sqft: 2122 },
  { municipality: 'Hatfield Township', address: '2108 N Line St', saleDate: '2026-06-19', salePrice: 450500, yearBuilt: 1956, beds: 1, baths: 1, sqft: 1098 },
  // --- Horsham -------------------------------------------------------------------
  { municipality: 'Horsham', address: '409 -b Saw Mill Ln', saleDate: '2026-07-08', salePrice: 500000, yearBuilt: 2001, beds: 3, baths: 2, halfBaths: 1, sqft: 1456 },
  { municipality: 'Horsham', address: '3 Hedgerow Ln', saleDate: '2026-07-06', salePrice: 635000, yearBuilt: 1986, beds: 4, baths: 2, halfBaths: 1, sqft: 2148 },
  { municipality: 'Horsham', address: '34 Green Woods Dr', saleDate: '2026-07-02', salePrice: 450000, yearBuilt: 1979, beds: 4, baths: 2, halfBaths: 1, sqft: 1918 },
  { municipality: 'Horsham', address: '113 Macintosh Ct', saleDate: '2026-07-01', salePrice: 420000, yearBuilt: 1987, beds: 2, baths: 2, sqft: 1899 },
  // --- Jenkintown ----------------------------------------------------------------
  { municipality: 'Jenkintown', address: '501 Rodman Ave', saleDate: '2026-07-08', salePrice: 905000, yearBuilt: 1930, beds: 4, baths: 3, halfBaths: 1, sqft: 3113 },
  { municipality: 'Jenkintown', address: '309 Highland Ave', saleDate: '2026-06-18', salePrice: 620000, yearBuilt: 1920, beds: 6, baths: 3, sqft: 3543 },
  { municipality: 'Jenkintown', address: '28 Indian Path Ln', saleDate: '2026-06-12', salePrice: 236000, yearBuilt: 1910, beds: 3, baths: 1, sqft: 1834 },
  { municipality: 'Jenkintown', address: '600 Runnymede Ave', saleDate: '2026-06-09', salePrice: 800000, yearBuilt: 1923, beds: 4, baths: 3, halfBaths: 1, sqft: 3334 },
  { municipality: 'Jenkintown', address: '404 Cheltena Ave', saleDate: '2026-06-08', salePrice: 567500, yearBuilt: 1924, beds: 4, baths: 1, sqft: 1750 },
  // --- Lansdale ------------------------------------------------------------------
  { municipality: 'Lansdale', address: '859 W Second St', saleDate: '2026-07-07', salePrice: 325000, yearBuilt: 1924, beds: 3, baths: 1, sqft: 1184 },
  { municipality: 'Lansdale', address: '106 Drake Ln', saleDate: '2026-07-02', salePrice: 219000, yearBuilt: 1915, beds: 3, baths: 1, sqft: 1242 },
  { municipality: 'Lansdale', address: '60 Hamilton St', saleDate: '2026-07-02', salePrice: 350000, yearBuilt: 1962, beds: 3, baths: 1, halfBaths: 1, sqft: 1000 },
  { municipality: 'Lansdale', address: '816 Kenilworth Ave', saleDate: '2026-07-02', salePrice: 437500, yearBuilt: 1930, beds: 3, baths: 2, sqft: 1202 },
  { municipality: 'Lansdale', address: '329 Columbia Ave', saleDate: '2026-07-01', salePrice: 380000, yearBuilt: 1910, beds: 5, baths: 1, sqft: 1414 },
  // --- Limerick ------------------------------------------------------------------
  { municipality: 'Limerick', address: '45 Jessica Cir', saleDate: '2026-06-30', salePrice: 675000, yearBuilt: 2000, beds: 4, baths: 2, halfBaths: 1, sqft: 2882 },
  { municipality: 'Limerick', address: '2620 Egypt Rd', saleDate: '2026-06-30', salePrice: 3400000, yearBuilt: 2002, beds: 4, baths: 6, halfBaths: 2, sqft: 9483 },
  { municipality: 'Limerick', address: '106 S Limerick Rd', saleDate: '2026-06-25', salePrice: 250000, yearBuilt: 1850, beds: 2, baths: 1, sqft: 1740 },
  { municipality: 'Limerick', address: '119 Bradford Dr', saleDate: '2026-06-24', salePrice: 930000, yearBuilt: 2001, beds: 4, baths: 2, halfBaths: 1, sqft: 4283 },
  { municipality: 'Limerick', address: '80 Graterford Rd', saleDate: '2026-06-24', salePrice: 730000, yearBuilt: 2005, beds: 3, baths: 2, halfBaths: 1, sqft: 2472 },
  // --- Lower Frederick -----------------------------------------------------------
  { municipality: 'Lower Frederick', address: '53 Game Farm Rd', saleDate: '2026-07-10', salePrice: 310000, yearBuilt: 1986, beds: 3, baths: 1, halfBaths: 1, sqft: 1200 },
  { municipality: 'Lower Frederick', address: '2451 Hoffmansville Rd', saleDate: '2026-06-25', salePrice: 422500, yearBuilt: 1986, beds: 3, baths: 1, sqft: 1392 },
  { municipality: 'Lower Frederick', address: '53 Steiner Way', saleDate: '2026-06-24', salePrice: 789885, yearBuilt: 2025, beds: 4, baths: 4, halfBaths: 1, sqft: 3756 },
  { municipality: 'Lower Frederick', address: '61 Steiner Way', saleDate: '2026-06-15', salePrice: 765620, yearBuilt: 2025, beds: 4, baths: 3, halfBaths: 1, sqft: 3562 },
  { municipality: 'Lower Frederick', address: '18 Perkiomen Ave', saleDate: '2026-06-11', salePrice: 415000, yearBuilt: 1935, beds: 3, baths: 1, sqft: 801 },
  // --- Lower Gwynedd -------------------------------------------------------------
  { municipality: 'Lower Gwynedd', address: '284 Conway Cir', saleDate: '2026-07-08', salePrice: 600000, yearBuilt: 1986, beds: 3, baths: 2, halfBaths: 1, sqft: 2197 },
  { municipality: 'Lower Gwynedd', address: '606 N Monroe St', saleDate: '2026-07-07', salePrice: 250000, yearBuilt: 1890, beds: 3, baths: 1, sqft: 1686 },
  { municipality: 'Lower Gwynedd', address: '2 Hedgerow Dr', saleDate: '2026-06-30', salePrice: 1400000, yearBuilt: 1978, beds: 5, baths: 2, halfBaths: 1, sqft: 3380 },
  { municipality: 'Lower Gwynedd', address: '431 Marion Ave', saleDate: '2026-06-26', salePrice: 424900, yearBuilt: 1952, beds: 3, baths: 1, halfBaths: 1, sqft: 1044 },
  { municipality: 'Lower Gwynedd', address: '34 Austin Cir', saleDate: '2026-06-25', salePrice: 1231000, yearBuilt: 1986, beds: 4, baths: 2, halfBaths: 1, sqft: 3041 },
  // --- Lower Merion --------------------------------------------------------------
  { municipality: 'Lower Merion', address: '138 Edgehill Rd', saleDate: '2026-07-09', salePrice: 515000, yearBuilt: 1925, beds: 3, baths: 1, halfBaths: 1, sqft: 1503 },
  { municipality: 'Lower Merion', address: '85 Price St', saleDate: '2026-07-08', salePrice: 450000, yearBuilt: 1930, beds: 3, baths: 2, sqft: 1684 },
  { municipality: 'Lower Merion', address: '1270 Round Hill Rd', saleDate: '2026-07-07', salePrice: 1300000, yearBuilt: 1986, beds: 4, baths: 4, halfBaths: 1, sqft: 3648 },
  { municipality: 'Lower Merion', address: '51 Academy Rd', saleDate: '2026-07-07', salePrice: 1326000, yearBuilt: 1964, beds: 5, baths: 2, halfBaths: 1, sqft: 2663 },
  { municipality: 'Lower Merion', address: '242 Henley Rd', saleDate: '2026-07-07', salePrice: 375000, yearBuilt: 1928, beds: 3, baths: 1, halfBaths: 1, sqft: 1206 },
  // --- Lower Moreland ------------------------------------------------------------
  { municipality: 'Lower Moreland', address: '3701 Levy Ln', saleDate: '2026-07-06', salePrice: 480000, yearBuilt: 1945, beds: 3, baths: 1, halfBaths: 1, sqft: 1568 },
  { municipality: 'Lower Moreland', address: '3936 Martin Rd', saleDate: '2026-06-30', salePrice: 776000, yearBuilt: 1959, beds: 3, baths: 2, sqft: 2036 },
  { municipality: 'Lower Moreland', address: '2771 Philmont Ave', saleDate: '2026-06-30', salePrice: 1750000, yearBuilt: 1960, beds: 5, baths: 3, halfBaths: 2, sqft: 4435 },
  { municipality: 'Lower Moreland', address: '407 Keats Rd', saleDate: '2026-06-29', salePrice: 625000, yearBuilt: 1960, beds: 3, baths: 2, halfBaths: 1, sqft: 2039 },
  { municipality: 'Lower Moreland', address: '2291 Packard Ave', saleDate: '2026-06-29', salePrice: 825000, yearBuilt: 1968, beds: 3, baths: 2, halfBaths: 1, sqft: 2891 },
  // --- Lower Pottsgrove ----------------------------------------------------------
  { municipality: 'Lower Pottsgrove', address: '23 Hunters Run', saleDate: '2026-07-09', salePrice: 520000, yearBuilt: 1997, beds: 4, baths: 2, halfBaths: 1, sqft: 2508 },
  { municipality: 'Lower Pottsgrove', address: '1165 Kepler Rd', saleDate: '2026-07-02', salePrice: 689000, yearBuilt: 1949, beds: 4, baths: 2, halfBaths: 1, sqft: 2727 },
  { municipality: 'Lower Pottsgrove', address: '128 Van Fleet Cir', saleDate: '2026-07-01', salePrice: 399900, yearBuilt: 2024, beds: 3, baths: 2, sqft: 1545 },
  { municipality: 'Lower Pottsgrove', address: '290 S Sanatoga Rd', saleDate: '2026-06-30', salePrice: 200000, yearBuilt: 1930, beds: 2, baths: 1, sqft: 960 },
  { municipality: 'Lower Pottsgrove', address: '2406 Donna Ln', saleDate: '2026-06-26', salePrice: 551000, yearBuilt: 1995, beds: 4, baths: 2, halfBaths: 1, sqft: 3276 },
  // --- Lower Providence ----------------------------------------------------------
  { municipality: 'Lower Providence', address: '22 Woodstock Cir', saleDate: '2026-07-09', salePrice: 760000, yearBuilt: 1978, beds: 4, baths: 2, halfBaths: 1, sqft: 2722 },
  { municipality: 'Lower Providence', address: '113 Belmont Ave', saleDate: '2026-06-29', salePrice: 459501, yearBuilt: 1950, beds: 3, baths: 2, sqft: 2129 },
  { municipality: 'Lower Providence', address: '1001 Michael Ln', saleDate: '2026-06-26', salePrice: 1130000, yearBuilt: 2004, beds: 4, baths: 2, halfBaths: 1, sqft: 3655 },
  { municipality: 'Lower Providence', address: '1012 Redtail Rd', saleDate: '2026-06-26', salePrice: 875000, yearBuilt: 1995, beds: 4, baths: 3, halfBaths: 1, sqft: 3307 },
  { municipality: 'Lower Providence', address: '2620 Egypt Rd', saleDate: '2026-06-25', salePrice: 630000, yearBuilt: 1960, beds: 4, baths: 2, halfBaths: 1, sqft: 2838 },
  // --- Lower Salford -------------------------------------------------------------
  { municipality: 'Lower Salford', address: '801 Upper Mainland Rd', saleDate: '2026-06-30', salePrice: 606000, yearBuilt: 1986, beds: 3, baths: 2, sqft: 2315 },
  { municipality: 'Lower Salford', address: '100 Cooke Way', saleDate: '2026-06-30', salePrice: 1502067, yearBuilt: 2026, beds: 4, baths: 4, halfBaths: 1, sqft: 4563 },
  { municipality: 'Lower Salford', address: '2 Creek View Ct', saleDate: '2026-06-29', salePrice: 460000, yearBuilt: 1979, beds: 4, baths: 1, halfBaths: 1, sqft: 1936 },
  { municipality: 'Lower Salford', address: '339 Maple Ave', saleDate: '2026-06-29', salePrice: 565000, yearBuilt: 1932, beds: 3, baths: 1, halfBaths: 1, sqft: 2020 },
  { municipality: 'Lower Salford', address: '645 Store Rd', saleDate: '2026-06-26', salePrice: 250000, yearBuilt: 1764, beds: 3, baths: 2, halfBaths: 1, sqft: 2884 },
  // --- Marlborough ---------------------------------------------------------------
  { municipality: 'Marlborough', address: '3675 Geryville Pike', saleDate: '2026-06-30', salePrice: 150000, yearBuilt: 1950, beds: 3, baths: 1, sqft: 1400 },
  { municipality: 'Marlborough', address: '4156 E Campbell Rd', saleDate: '2026-06-22', salePrice: 450000, yearBuilt: 1954, beds: 3, baths: 1, halfBaths: 1, sqft: 1624 },
  { municipality: 'Marlborough', address: '3829 Geryville Pike', saleDate: '2026-06-08', salePrice: 350000, yearBuilt: 1955, beds: 3, baths: 1, sqft: 1215 },
  { municipality: 'Marlborough', address: '103 Gravel Pike', saleDate: '2026-06-05', salePrice: 365000, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1480 },
  { municipality: 'Marlborough', address: '2765 W Unami Cir', saleDate: '2026-05-29', salePrice: 705000, yearBuilt: 1984, beds: 4, baths: 2, halfBaths: 1, sqft: 2520 },
  // --- Montgomery Township -------------------------------------------------------
  { municipality: 'Montgomery Township', address: '150 Country Club Dr', saleDate: '2026-07-07', salePrice: 560000, yearBuilt: 1990, beds: 3, baths: 2, halfBaths: 1, sqft: 2560 },
  { municipality: 'Montgomery Township', address: '106 Avondale Dr', saleDate: '2026-07-01', salePrice: 887000, yearBuilt: 2006, beds: 4, baths: 2, halfBaths: 1, sqft: 3251 },
  { municipality: 'Montgomery Township', address: '150 Country Club Dr', saleDate: '2026-07-01', salePrice: 572000, yearBuilt: 1995, beds: 3, baths: 2, halfBaths: 1, sqft: 2310 },
  { municipality: 'Montgomery Township', address: '303 Stratford Ct', saleDate: '2026-06-30', salePrice: 450000, yearBuilt: 1988, beds: 3, baths: 2, halfBaths: 1, sqft: 1431 },
  { municipality: 'Montgomery Township', address: '214 Broad Acres Rd', saleDate: '2026-06-24', salePrice: 900000, yearBuilt: 1990, beds: 4, baths: 2, halfBaths: 1, sqft: 3216 },
  // --- Narberth ------------------------------------------------------------------
  { municipality: 'Narberth', address: '307 Woodbine Ave', saleDate: '2026-07-08', salePrice: 290000, yearBuilt: 1910, beds: 3, baths: 1, sqft: 1132 },
  { municipality: 'Narberth', address: '318 Dudley Ave', saleDate: '2026-06-30', salePrice: 1433600, yearBuilt: 1915, beds: 3, baths: 1, sqft: 1056 },
  { municipality: 'Narberth', address: '408 Conway Ave', saleDate: '2026-06-24', salePrice: 503750, yearBuilt: 1960, beds: 3, baths: 1, halfBaths: 1, sqft: 1224 },
  { municipality: 'Narberth', address: '200 Sabine Ave', saleDate: '2026-06-22', salePrice: 1050000, yearBuilt: 1910, beds: 4, baths: 3, sqft: 2299 },
  { municipality: 'Narberth', address: '204 Grayling Ave', saleDate: '2026-06-09', salePrice: 737500, yearBuilt: 1900, beds: 6, baths: 3, sqft: 3638 },
  // --- New Hanover ---------------------------------------------------------------
  { municipality: 'New Hanover', address: '445 Moyer Rd', saleDate: '2026-07-04', salePrice: 385000, yearBuilt: 1960, beds: 3, baths: 1, sqft: 1102 },
  { municipality: 'New Hanover', address: '607 Kulp Rd', saleDate: '2026-07-02', salePrice: 551000, yearBuilt: 1984, beds: 3, baths: 2, sqft: 1624 },
  { municipality: 'New Hanover', address: '2951 Burton Dr', saleDate: '2026-06-30', salePrice: 660000, yearBuilt: 2004, beds: 3, baths: 2, sqft: 3913 },
  { municipality: 'New Hanover', address: '2394 Hill Rd', saleDate: '2026-06-29', salePrice: 534900, yearBuilt: 1975, beds: 4, baths: 2, sqft: 2340 },
  { municipality: 'New Hanover', address: '108 Matthew Ln', saleDate: '2026-06-29', salePrice: 725000, yearBuilt: 2010, beds: 3, baths: 2, halfBaths: 1, sqft: 2947 },
  // --- Norristown ----------------------------------------------------------------
  { municipality: 'Norristown', address: '517 Glenn Valley Dr', saleDate: '2026-07-02', salePrice: 260000, yearBuilt: 1960, beds: 3, baths: 1, halfBaths: 1, sqft: 1200 },
  { municipality: 'Norristown', address: '1724 Kendrick Ln', saleDate: '2026-06-29', salePrice: 320000, yearBuilt: 1960, beds: 3, baths: 1, halfBaths: 1, sqft: 1184 },
  { municipality: 'Norristown', address: '700 Hamilton St', saleDate: '2026-06-28', salePrice: 404000, yearBuilt: 1949, beds: 2, baths: 1, sqft: 1391 },
  { municipality: 'Norristown', address: '1505 Astor St', saleDate: '2026-06-26', salePrice: 195000, yearBuilt: 1924, beds: 3, baths: 1, halfBaths: 1, sqft: 1664 },
  { municipality: 'Norristown', address: '1703 Powell St', saleDate: '2026-06-26', salePrice: 261000, yearBuilt: 1928, beds: 3, baths: 1, sqft: 1300 },
  // --- North Wales ---------------------------------------------------------------
  { municipality: 'North Wales', address: '136 N Swartley St', saleDate: '2026-06-26', salePrice: 265000, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1088 },
  { municipality: 'North Wales', address: '6042 Peacock Ct', saleDate: '2026-06-11', salePrice: 425000, yearBuilt: 1900, beds: 5, baths: 1, halfBaths: 1, sqft: 1780 },
  { municipality: 'North Wales', address: '323 S Fifth St', saleDate: '2026-06-04', salePrice: 557500, yearBuilt: 1959, beds: 4, baths: 1, halfBaths: 1, sqft: 1615 },
  { municipality: 'North Wales', address: '1509 Taylor Rd', saleDate: '2026-05-28', salePrice: 204000, yearBuilt: 1935, beds: 3, baths: 1, sqft: 811 },
  { municipality: 'North Wales', address: '627 Perkiomen Ave', saleDate: '2026-05-26', salePrice: 212100, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1064 },
  // --- Pennsburg -----------------------------------------------------------------
  { municipality: 'Pennsburg', address: '6094 Main St', saleDate: '2026-06-18', salePrice: 245000, yearBuilt: 1972, beds: 3, baths: 1, halfBaths: 1, sqft: 1280 },
  { municipality: 'Pennsburg', address: '769 Hunter Dr', saleDate: '2026-06-16', salePrice: 320000, yearBuilt: 2005, beds: 3, baths: 2, halfBaths: 1, sqft: 1795 },
  { municipality: 'Pennsburg', address: '210 Shirley Ln', saleDate: '2026-05-29', salePrice: 415000, yearBuilt: 2001, beds: 3, baths: 2, halfBaths: 1, sqft: 2244 },
  { municipality: 'Pennsburg', address: '730 Fawn Way', saleDate: '2026-05-29', salePrice: 414990, yearBuilt: 2026, beds: 3, baths: 2, halfBaths: 1, sqft: 1864 },
  { municipality: 'Pennsburg', address: '3256 Miller Rd', saleDate: '2026-05-28', salePrice: 200000, yearBuilt: 1947, beds: 3, baths: 1, sqft: 1152 },
  // --- Perkiomen -----------------------------------------------------------------
  { municipality: 'Perkiomen', address: '810 Elizabeth Ct', saleDate: '2026-07-02', salePrice: 598000, yearBuilt: 1998, beds: 3, baths: 2, halfBaths: 1, sqft: 1716 },
  { municipality: 'Perkiomen', address: '1116 Pheasant Ln', saleDate: '2026-07-02', salePrice: 325000, yearBuilt: 1862, beds: 4, baths: 1, halfBaths: 1, sqft: 1529 },
  { municipality: 'Perkiomen', address: '117 Raleigh Rd', saleDate: '2026-06-23', salePrice: 655000, yearBuilt: 1995, beds: 4, baths: 2, halfBaths: 1, sqft: 2464 },
  { municipality: 'Perkiomen', address: '606 Buyers Rd', saleDate: '2026-06-23', salePrice: 290000, yearBuilt: 1975, beds: 3, baths: 2, halfBaths: 1, sqft: 1276 },
  { municipality: 'Perkiomen', address: '630 Stewart Rd', saleDate: '2026-06-16', salePrice: 535000, yearBuilt: 1997, beds: 3, baths: 2, halfBaths: 1, sqft: 1716 },
  // --- Plymouth ------------------------------------------------------------------
  { municipality: 'Plymouth', address: '1430 Colwell Ln', saleDate: '2026-07-09', salePrice: 419000, yearBuilt: 1979, beds: 3, baths: 1, halfBaths: 1, sqft: 1000 },
  { municipality: 'Plymouth', address: '666 W Germantown Pike Unit 2213', saleDate: '2026-06-30', salePrice: 335000, yearBuilt: 1974, beds: 2, baths: 2, sqft: 1196 },
  { municipality: 'Plymouth', address: '392 Leroy St', saleDate: '2026-06-30', salePrice: 325000, yearBuilt: 1958, beds: 2, baths: 1, sqft: 990 },
  { municipality: 'Plymouth', address: '107 Alexander Dr', saleDate: '2026-06-30', salePrice: 1300000, yearBuilt: 2022, beds: 4, baths: 3, halfBaths: 1, sqft: 3110 },
  // --- Pottstown -----------------------------------------------------------------
  { municipality: 'Pottstown', address: '665 Woodland Ave', saleDate: '2026-07-09', salePrice: 265000, yearBuilt: 1953, beds: 3, baths: 1, halfBaths: 1, sqft: 1158 },
  { municipality: 'Pottstown', address: '804 Queen St', saleDate: '2026-07-08', salePrice: 230000, yearBuilt: 1900, beds: 4, baths: 1, sqft: 1610 },
  { municipality: 'Pottstown', address: '2052 Prout Farm Rd', saleDate: '2026-07-02', salePrice: 230000, yearBuilt: 1920, beds: 3, baths: 1, sqft: 1328 },
  { municipality: 'Pottstown', address: '431 Cherry St', saleDate: '2026-07-02', salePrice: 280000, yearBuilt: 1900, beds: 2, baths: 1, sqft: 1210 },
  { municipality: 'Pottstown', address: '897 N Adams St', saleDate: '2026-06-30', salePrice: 302500, yearBuilt: 1950, beds: 4, baths: 1, sqft: 1021 },
  // --- Red Hill ------------------------------------------------------------------
  { municipality: 'Red Hill', address: '330 Wexford Rd Rm 221', saleDate: '2026-07-10', salePrice: 385000, yearBuilt: 1973, beds: 3, baths: 1, halfBaths: 1, sqft: 1973 },
  { municipality: 'Red Hill', address: '113 Thorndale Dr', saleDate: '2026-06-30', salePrice: 325000, yearBuilt: 2006, beds: 3, baths: 2, halfBaths: 1, sqft: 1800 },
  { municipality: 'Red Hill', address: '208 W Third St', saleDate: '2026-06-25', salePrice: 439900, yearBuilt: 1973, beds: 3, baths: 1, halfBaths: 1, sqft: 1848 },
  { municipality: 'Red Hill', address: '3078 Martha Way', saleDate: '2026-06-25', salePrice: 427620, yearBuilt: 2026, beds: 3, baths: 2, halfBaths: 1, sqft: 1860 },
  { municipality: 'Red Hill', address: '4748 York Dr', saleDate: '2026-06-23', salePrice: 449120, yearBuilt: 2026, beds: 3, baths: 2, halfBaths: 1, sqft: 1860 },
  // --- Rockledge -----------------------------------------------------------------
  { municipality: 'Rockledge', address: '211 N Sylvania Ave', saleDate: '2026-07-06', salePrice: 461000, yearBuilt: 1922, beds: 3, baths: 1, sqft: 1454 },
  { municipality: 'Rockledge', address: '19 Loney St', saleDate: '2026-06-24', salePrice: 335000, yearBuilt: 1978, beds: 2, baths: 1, halfBaths: 1, sqft: 880 },
  { municipality: 'Rockledge', address: '8 Brighton Pl', saleDate: '2026-06-23', salePrice: 175000, yearBuilt: 1968, beds: 2, baths: 1, halfBaths: 1, sqft: 1008 },
  { municipality: 'Rockledge', address: '464 Elm Ave', saleDate: '2026-06-09', salePrice: 300000, yearBuilt: 1939, beds: 3, baths: 1, sqft: 1216 },
  { municipality: 'Rockledge', address: '720 Bobwhite Ln', saleDate: '2026-06-09', salePrice: 420000, yearBuilt: 1964, beds: 4, baths: 2, sqft: 1504 },
  // --- Royersford ----------------------------------------------------------------
  { municipality: 'Royersford', address: '771 Church St', saleDate: '2026-07-01', salePrice: 600000, yearBuilt: 1900, beds: 3, baths: 2, sqft: 2380 },
  { municipality: 'Royersford', address: '630 Oak St', saleDate: '2026-06-26', salePrice: 514000, yearBuilt: 1962, beds: 3, baths: 2, sqft: 1678 },
  { municipality: 'Royersford', address: '920 Chestnut St', saleDate: '2026-06-22', salePrice: 420000, yearBuilt: 1996, beds: 3, baths: 2, sqft: 2058 },
  { municipality: 'Royersford', address: '307 Spring St', saleDate: '2026-06-18', salePrice: 325000, yearBuilt: 1901, beds: 3, baths: 1, sqft: 1474 },
  { municipality: 'Royersford', address: '400 S Third Ave', saleDate: '2026-06-18', salePrice: 351000, yearBuilt: 1930, beds: 3, baths: 1, sqft: 1121 },
  // --- Salford -------------------------------------------------------------------
  { municipality: 'Salford', address: '661 Meadow Ln', saleDate: '2026-06-29', salePrice: 350000, yearBuilt: 2013, beds: 3, baths: 2, halfBaths: 1, sqft: 1595 },
  { municipality: 'Salford', address: '26 Salford Way', saleDate: '2026-06-25', salePrice: 880000, yearBuilt: 2004, beds: 4, baths: 2, halfBaths: 1, sqft: 3264 },
  { municipality: 'Salford', address: '23 Hausman Rd', saleDate: '2026-06-25', salePrice: 374600, yearBuilt: 1977, beds: 3, baths: 2, halfBaths: 1, sqft: 1904 },
  { municipality: 'Salford', address: '95 Cowpath Rd', saleDate: '2026-06-18', salePrice: 915000, yearBuilt: 2000, beds: 4, baths: 3, sqft: 3226 },
  { municipality: 'Salford', address: '288 Clump Rd', saleDate: '2026-06-05', salePrice: 895400, yearBuilt: 1997, beds: 3, baths: 2, halfBaths: 1, sqft: 3795 },
  // --- Schwenksville -------------------------------------------------------------
  { municipality: 'Schwenksville', address: '109 Woodland Ave', saleDate: '2026-06-22', salePrice: 395000, yearBuilt: 1964, beds: 3, baths: 1, sqft: 1040 },
  { municipality: 'Schwenksville', address: '908 Summit Ave', saleDate: '2026-06-03', salePrice: 486500, yearBuilt: 1930, beds: 3, baths: 1, sqft: 1536 },
  { municipality: 'Schwenksville', address: '725 Mine Hill Rd', saleDate: '2026-05-15', salePrice: 381500, yearBuilt: 1959, beds: 3, baths: 1, sqft: 1204 },
  { municipality: 'Schwenksville', address: '37 Pennypacker Dr', saleDate: '2026-02-17', salePrice: 259900, yearBuilt: 1988, beds: 3, baths: 1, halfBaths: 1, sqft: 1200 },
  { municipality: 'Schwenksville', address: '2220 Hendricks Station Rd', saleDate: '2026-01-14', salePrice: 302500, yearBuilt: 1953, beds: 2, baths: 2, sqft: 1526 },
  // --- Skippack ------------------------------------------------------------------
  { municipality: 'Skippack', address: '2223 Cooper Dr', saleDate: '2026-07-02', salePrice: 620703, yearBuilt: 2015, beds: 2, baths: 2, sqft: 1786 },
  { municipality: 'Skippack', address: '546 Heiser Rd', saleDate: '2026-06-30', salePrice: 490000, yearBuilt: 1962, beds: 4, baths: 1, sqft: 900 },
  { municipality: 'Skippack', address: '484 Mockingbird Ln', saleDate: '2026-06-30', salePrice: 830000, yearBuilt: 1989, beds: 4, baths: 2, halfBaths: 1, sqft: 2910 },
  { municipality: 'Skippack', address: '3888 Ashland Dr Unit B', saleDate: '2026-06-30', salePrice: 290000, yearBuilt: 2015, beds: 2, baths: 1, sqft: 788 },
  { municipality: 'Skippack', address: '752 Jubb Ln', saleDate: '2026-06-29', salePrice: 1735077, yearBuilt: 2026, beds: 4, baths: 3, halfBaths: 1, sqft: 4178 },
  // --- Souderton -----------------------------------------------------------------
  { municipality: 'Souderton', address: '834 Arrowhead Ln', saleDate: '2026-06-29', salePrice: 252000, yearBuilt: 1956, beds: 2, baths: 1, sqft: 1092 },
  { municipality: 'Souderton', address: '234 W Chestnut St', saleDate: '2026-06-24', salePrice: 435000, yearBuilt: 1955, beds: 3, baths: 1, halfBaths: 1, sqft: 1441 },
  { municipality: 'Souderton', address: '124 West St', saleDate: '2026-06-18', salePrice: 352000, yearBuilt: 1952, beds: 3, baths: 1, sqft: 936 },
  { municipality: 'Souderton', address: '40 Adams Ave', saleDate: '2026-06-18', salePrice: 325000, yearBuilt: 1930, beds: 3, baths: 1, sqft: 1218 },
  { municipality: 'Souderton', address: '39 Penn Ave', saleDate: '2026-06-05', salePrice: 355000, yearBuilt: 1900, beds: 3, baths: 1, sqft: 1359 },
  // --- Springfield Township --------------------------------------------------
  { municipality: 'Springfield Township', address: '2252 Bustard Rd', saleDate: '2026-07-13', salePrice: 450000, yearBuilt: 1940, beds: 3, baths: 1, sqft: 1410 },
  { municipality: 'Springfield Township', address: '1 Franklin Town Blvd Apt 911', saleDate: '2026-07-01', salePrice: 520000, yearBuilt: 1951, beds: 4, baths: 2, sqft: 1389 },
  { municipality: 'Springfield Township', address: '29 Bryn Mawr Ave', saleDate: '2026-06-30', salePrice: 430000, yearBuilt: 1957, beds: 4, baths: 2, sqft: 1848 },
  { municipality: 'Springfield Township', address: '510 Auburn Ave', saleDate: '2026-06-25', salePrice: 2400000, yearBuilt: 2006, beds: 6, baths: 5, halfBaths: 2, sqft: 6624 },
  // --- Telford -------------------------------------------------------------------
  { municipality: 'Telford', address: '11 Kynlyn Cir', saleDate: '2026-07-01', salePrice: 225000, yearBuilt: 1970, beds: 3, baths: 1, halfBaths: 1, sqft: 1221 },
  { municipality: 'Telford', address: '42 W Hamlin Ave', saleDate: '2026-06-30', salePrice: 290000, yearBuilt: 1915, beds: 3, baths: 1, sqft: 1581 },
  { municipality: 'Telford', address: '1600 Hartford Cir', saleDate: '2026-06-18', salePrice: 460000, yearBuilt: 2017, beds: 3, baths: 2, halfBaths: 1, sqft: 1922 },
  { municipality: 'Telford', address: '79 Central Ave', saleDate: '2026-06-17', salePrice: 530000, yearBuilt: 1950, beds: 3, baths: 2, sqft: 2746 },
  { municipality: 'Telford', address: '496 W Broad St', saleDate: '2026-06-12', salePrice: 415000, yearBuilt: 1875, beds: 3, baths: 1, halfBaths: 1, sqft: 2529 },
  // --- Towamencin ----------------------------------------------------------------
  { municipality: 'Towamencin', address: '1820 Pennland Ct', saleDate: '2026-07-10', salePrice: 301000, yearBuilt: 1976, beds: 3, baths: 1, halfBaths: 1, sqft: 1224 },
  { municipality: 'Towamencin', address: '870 Penn Oak Rd', saleDate: '2026-07-09', salePrice: 345000, yearBuilt: 1996, beds: 3, baths: 1, halfBaths: 1, sqft: 1488 },
  { municipality: 'Towamencin', address: '19 Victoria Ct', saleDate: '2026-07-08', salePrice: 500000, yearBuilt: 2004, beds: 3, baths: 2, halfBaths: 1, sqft: 1856 },
  { municipality: 'Towamencin', address: '27 Westhampton Way', saleDate: '2026-07-08', salePrice: 530000, yearBuilt: 2004, beds: 2, baths: 2, halfBaths: 1, sqft: 2025 },
  { municipality: 'Towamencin', address: '5 Camelot Way', saleDate: '2026-07-01', salePrice: 850000, yearBuilt: 2004, beds: 4, baths: 3, sqft: 3126 },
  // --- Trappe --------------------------------------------------------------------
  { municipality: 'Trappe', address: '171 W Main St', saleDate: '2026-06-30', salePrice: 440000, yearBuilt: 1927, beds: 3, baths: 1, sqft: 1264 },
  { municipality: 'Trappe', address: '312 E Seventh Ave', saleDate: '2026-06-30', salePrice: 580000, yearBuilt: 1953, beds: 2, baths: 1, halfBaths: 1, sqft: 2097 },
  { municipality: 'Trappe', address: '38 Ursinus Ave', saleDate: '2026-06-26', salePrice: 570000, yearBuilt: 1957, beds: 3, baths: 1, sqft: 1382 },
  { municipality: 'Trappe', address: '188 W Third Ave', saleDate: '2026-06-22', salePrice: 935000, yearBuilt: 2026, beds: 4, baths: 4, halfBaths: 1, sqft: 3493 },
  { municipality: 'Trappe', address: '13 Scholl Dr', saleDate: '2026-06-22', salePrice: 1084000, yearBuilt: 2026, beds: 4, baths: 4, halfBaths: 1, sqft: 4542 },
  // --- Upper Dublin --------------------------------------------------------------
  { municipality: 'Upper Dublin', address: '430 Renfrew Ave', saleDate: '2026-07-06', salePrice: 395000, yearBuilt: 1911, beds: 3, baths: 1, sqft: 1224 },
  { municipality: 'Upper Dublin', address: '1619 Shepard Dr', saleDate: '2026-07-01', salePrice: 900000, yearBuilt: 1962, beds: 5, baths: 3, halfBaths: 1, sqft: 2585 },
  { municipality: 'Upper Dublin', address: '1547 Oregon Pike', saleDate: '2026-06-30', salePrice: 485000, yearBuilt: 1960, beds: 4, baths: 2, halfBaths: 1, sqft: 2174 },
  { municipality: 'Upper Dublin', address: '118 Clarrige Dr', saleDate: '2026-06-29', salePrice: 590000, yearBuilt: 1963, beds: 3, baths: 2, halfBaths: 1, sqft: 1912 },
  { municipality: 'Upper Dublin', address: '1790 Twining Rd', saleDate: '2026-06-25', salePrice: 558000, yearBuilt: 1976, beds: 3, baths: 2, halfBaths: 1, sqft: 1260 },
  // --- Upper Frederick -----------------------------------------------------------
  { municipality: 'Upper Frederick', address: '2942 Baas Rd', saleDate: '2026-06-18', salePrice: 665000, yearBuilt: 1978, beds: 4, baths: 2, halfBaths: 1, sqft: 2317 },
  { municipality: 'Upper Frederick', address: '105 Ivy Ln', saleDate: '2026-06-15', salePrice: 455000, yearBuilt: 2002, beds: 3, baths: 2, halfBaths: 1, sqft: 1676 },
  { municipality: 'Upper Frederick', address: '3415 Foxfield Cir', saleDate: '2026-06-10', salePrice: 335000, yearBuilt: 1991, beds: 3, baths: 2, halfBaths: 1, sqft: 1586 },
  { municipality: 'Upper Frederick', address: '1847 Gravel Pike', saleDate: '2026-06-05', salePrice: 740000, yearBuilt: 1920, beds: 4, baths: 2, sqft: 3293 },
  { municipality: 'Upper Frederick', address: '1262 Hunter Ln', saleDate: '2026-06-05', salePrice: 375000, yearBuilt: 2000, beds: 3, baths: 2, halfBaths: 1, sqft: 1764 },
  // --- Upper Gwynedd -------------------------------------------------------------
  { municipality: 'Upper Gwynedd', address: '786 Keith Ln', saleDate: '2026-07-08', salePrice: 400000, yearBuilt: 1987, beds: 3, baths: 2, halfBaths: 1, sqft: 1412 },
  { municipality: 'Upper Gwynedd', address: '137 Dawn Dr', saleDate: '2026-06-29', salePrice: 345000, yearBuilt: 1991, beds: 2, baths: 1, halfBaths: 1, sqft: 1004 },
  { municipality: 'Upper Gwynedd', address: '1156 Kipling Ct', saleDate: '2026-06-26', salePrice: 515000, yearBuilt: 1991, beds: 3, baths: 2, halfBaths: 1, sqft: 2137 },
  { municipality: 'Upper Gwynedd', address: '107 Noble Ct', saleDate: '2026-06-26', salePrice: 325000, yearBuilt: 1955, beds: 3, baths: 1, sqft: 1056 },
  { municipality: 'Upper Gwynedd', address: '1421 Cathy S Ln', saleDate: '2026-06-23', salePrice: 565000, yearBuilt: 1968, beds: 4, baths: 2, halfBaths: 1, sqft: 1899 },
  // --- Upper Hanover -------------------------------------------------------------
  { municipality: 'Upper Hanover', address: '2100 Atwood Ter', saleDate: '2026-06-30', salePrice: 426000, yearBuilt: 2014, beds: 3, baths: 2, halfBaths: 1, sqft: 2063 },
  { municipality: 'Upper Hanover', address: '2039 Bethesda Church Rd', saleDate: '2026-06-29', salePrice: 615000, yearBuilt: 2004, beds: 4, baths: 2, halfBaths: 1, sqft: 2576 },
  { municipality: 'Upper Hanover', address: '2190 E Buck Rd', saleDate: '2026-06-26', salePrice: 505000, yearBuilt: 1920, beds: 4, baths: 1, halfBaths: 1, sqft: 4258 },
  { municipality: 'Upper Hanover', address: '2045 Adams Rd', saleDate: '2026-06-25', salePrice: 460000, yearBuilt: 1985, beds: 5, baths: 2, halfBaths: 1, sqft: 2055 },
  { municipality: 'Upper Hanover', address: '1005 Glasco Dr', saleDate: '2026-06-24', salePrice: 1002828, yearBuilt: 2026, beds: 4, baths: 2, halfBaths: 2, sqft: 4174 },
  // --- Upper Merion --------------------------------------------------------------
  { municipality: 'Upper Merion', address: '174 Mahogany Ln', saleDate: '2026-07-09', salePrice: 710000, yearBuilt: 2024, beds: 3, baths: 2, halfBaths: 1, sqft: 1952 },
  { municipality: 'Upper Merion', address: '560 Susan Dr', saleDate: '2026-07-07', salePrice: 547500, yearBuilt: 1985, beds: 3, baths: 2, halfBaths: 1, sqft: 1684 },
  { municipality: 'Upper Merion', address: '1211 Reed Alley', saleDate: '2026-07-07', salePrice: 575000, yearBuilt: 2022, beds: 3, baths: 2, halfBaths: 1, sqft: 1995 },
  { municipality: 'Upper Merion', address: '159 Crooked Ln', saleDate: '2026-07-01', salePrice: 382500, yearBuilt: 1921, beds: 4, baths: 1, sqft: 1748 },
  { municipality: 'Upper Merion', address: '329 Glenn Rose Cir', saleDate: '2026-06-26', salePrice: 510000, yearBuilt: 2000, beds: 3, baths: 2, halfBaths: 1, sqft: 2066 },
  // --- Upper Moreland ------------------------------------------------------------
  { municipality: 'Upper Moreland', address: '402 Evans Ave', saleDate: '2026-07-01', salePrice: 475000, yearBuilt: 1943, beds: 3, baths: 1, sqft: 1330 },
  { municipality: 'Upper Moreland', address: '4185 Shoemaker Rd', saleDate: '2026-06-30', salePrice: 650000, yearBuilt: 1985, beds: 4, baths: 2, halfBaths: 1, sqft: 2536 },
  { municipality: 'Upper Moreland', address: '18 Church St', saleDate: '2026-06-30', salePrice: 330000, yearBuilt: 1925, beds: 5, baths: 1, sqft: 1578 },
  { municipality: 'Upper Moreland', address: '416 Exton Rd', saleDate: '2026-06-29', salePrice: 437000, yearBuilt: 1945, beds: 3, baths: 1, halfBaths: 1, sqft: 1424 },
  { municipality: 'Upper Moreland', address: '223 Fitzwatertown Rd', saleDate: '2026-06-29', salePrice: 379000, yearBuilt: 1955, beds: 2, baths: 1, sqft: 936 },
  // --- Upper Pottsgrove ----------------------------------------------------------
  { municipality: 'Upper Pottsgrove', address: '949 Pennsylvania Ave', saleDate: '2026-06-26', salePrice: 440000, yearBuilt: 1955, beds: 3, baths: 1, halfBaths: 1, sqft: 1215 },
  { municipality: 'Upper Pottsgrove', address: '173 Lilly Dr', saleDate: '2026-06-20', salePrice: 439500, yearBuilt: 2022, beds: 4, baths: 2, sqft: 1718 },
  { municipality: 'Upper Pottsgrove', address: '500 Anthonys Dr', saleDate: '2026-06-18', salePrice: 217000, yearBuilt: 1976, beds: 4, baths: 2, sqft: 1638 },
  { municipality: 'Upper Pottsgrove', address: '1537 Meadowview Dr', saleDate: '2026-06-16', salePrice: 520000, yearBuilt: 1997, beds: 4, baths: 2, halfBaths: 1, sqft: 2224 },
  { municipality: 'Upper Pottsgrove', address: '2072 Yarnall Rd', saleDate: '2026-06-05', salePrice: 443000, yearBuilt: 1958, beds: 3, baths: 1, sqft: 1322 },
  // --- Upper Providence ----------------------------------------------------------
  { municipality: 'Upper Providence', address: '11 Iroquois Dr', saleDate: '2026-07-09', salePrice: 390000, yearBuilt: 1975, beds: 3, baths: 2, halfBaths: 1, sqft: 1550 },
  { municipality: 'Upper Providence', address: '1046 S Trappe Rd', saleDate: '2026-07-07', salePrice: 625000, yearBuilt: 1800, beds: 3, baths: 2, sqft: 2160 },
  { municipality: 'Upper Providence', address: '214 Hanover Rd', saleDate: '2026-07-01', salePrice: 760000, yearBuilt: 2007, beds: 2, baths: 2, sqft: 2858 },
  { municipality: 'Upper Providence', address: '59 Orchard Ct', saleDate: '2026-06-30', salePrice: 325000, yearBuilt: 1975, beds: 3, baths: 1, halfBaths: 1, sqft: 1460 },
  { municipality: 'Upper Providence', address: '132 Chinaberry Ln', saleDate: '2026-06-30', salePrice: 955125, yearBuilt: 1998, beds: 4, baths: 2, halfBaths: 1, sqft: 3886 },
  // --- Upper Salford -------------------------------------------------------------
  { municipality: 'Upper Salford', address: '2680 Shelly Rd', saleDate: '2026-07-01', salePrice: 980000, yearBuilt: 1986, beds: 3, baths: 2, halfBaths: 1, sqft: 2525 },
  { municipality: 'Upper Salford', address: '941 Salford Station Rd', saleDate: '2026-06-25', salePrice: 400000, yearBuilt: 1968, beds: 3, baths: 2, sqft: 1540 },
  { municipality: 'Upper Salford', address: '1743 Yarnall Rd', saleDate: '2026-06-19', salePrice: 125000, yearBuilt: 1978, beds: 3, baths: 1, sqft: 840 },
  { municipality: 'Upper Salford', address: '2871 Heather Dr', saleDate: '2026-06-12', salePrice: 459000, yearBuilt: 1972, beds: 4, baths: 2, sqft: 2432 },
  { municipality: 'Upper Salford', address: '2125 Salford St', saleDate: '2026-06-12', salePrice: 689999, yearBuilt: 2001, beds: 3, baths: 2, halfBaths: 1, sqft: 2068 },
  // --- West Conshohocken ---------------------------------------------------------
  { municipality: 'West Conshohocken', address: '416 Spring Garden Ln', saleDate: '2026-06-19', salePrice: 910000, yearBuilt: 1998, beds: 4, baths: 3, halfBaths: 1, sqft: 4820 },
  { municipality: 'West Conshohocken', address: '1119 Riverview Ln', saleDate: '2026-06-05', salePrice: 785000, yearBuilt: 1999, beds: 3, baths: 3, halfBaths: 1, sqft: 3596 },
  { municipality: 'West Conshohocken', address: '407 Merion Hill Ln', saleDate: '2026-05-29', salePrice: 879500, yearBuilt: 1998, beds: 4, baths: 3, halfBaths: 1, sqft: 3659 },
  { municipality: 'West Conshohocken', address: '102 Campbell Dr', saleDate: '2026-05-28', salePrice: 535000, yearBuilt: 1995, beds: 2, baths: 2, halfBaths: 1, sqft: 1920 },
  { municipality: 'West Conshohocken', address: '221 Ford St', saleDate: '2026-05-23', salePrice: 610000, yearBuilt: 1875, beds: 4, baths: 1, sqft: 1640 },
  // --- West Norriton -------------------------------------------------------------
  { municipality: 'West Norriton', address: '2116 Weber Ln', saleDate: '2026-07-09', salePrice: 250000, yearBuilt: 1954, beds: 3, baths: 1, halfBaths: 1, sqft: 1279 },
  { municipality: 'West Norriton', address: '202 Stonybrook Dr Unit 202', saleDate: '2026-07-08', salePrice: 335000, yearBuilt: 1975, beds: 3, baths: 2, halfBaths: 1, sqft: 2019 },
  { municipality: 'West Norriton', address: '230 Oxford Cir', saleDate: '2026-07-06', salePrice: 395000, yearBuilt: 1950, beds: 4, baths: 1, sqft: 1684 },
  { municipality: 'West Norriton', address: '110 Colonial Ave', saleDate: '2026-07-02', salePrice: 452000, yearBuilt: 1956, beds: 4, baths: 1, halfBaths: 1, sqft: 2696 },
  { municipality: 'West Norriton', address: '538 Canterbury Rd', saleDate: '2026-06-30', salePrice: 296000, yearBuilt: 1985, beds: 2, baths: 1, halfBaths: 1, sqft: 1080 },
  // --- West Pottsgrove -----------------------------------------------------------
  { municipality: 'West Pottsgrove', address: '659 Old Reading Pike', saleDate: '2026-07-06', salePrice: 155000, yearBuilt: 1920, beds: 3, baths: 1, sqft: 1120 },
  { municipality: 'West Pottsgrove', address: '951 Grosstown Rd', saleDate: '2026-07-02', salePrice: 400000, yearBuilt: 1940, beds: 4, baths: 2, sqft: 2340 },
  { municipality: 'West Pottsgrove', address: '2137 Justice Ln', saleDate: '2026-06-24', salePrice: 340000, yearBuilt: 1920, beds: 2, baths: 1, halfBaths: 1, sqft: 1610 },
  { municipality: 'West Pottsgrove', address: '29 Foxchase Ln', saleDate: '2026-06-19', salePrice: 157500, yearBuilt: 1890, beds: 3, baths: 1, halfBaths: 1, sqft: 1613 },
  { municipality: 'West Pottsgrove', address: '113 Linden St', saleDate: '2026-06-17', salePrice: 354000, yearBuilt: 1920, beds: 2, baths: 1, halfBaths: 1, sqft: 1676 },
  // --- Whitemarsh ----------------------------------------------------------------
  { municipality: 'Whitemarsh', address: '2140 Ash Ln', saleDate: '2026-07-09', salePrice: 460000, yearBuilt: 1976, beds: 3, baths: 1, halfBaths: 1, sqft: 1614 },
  { municipality: 'Whitemarsh', address: '272 E North Ln', saleDate: '2026-07-07', salePrice: 565000, yearBuilt: 1939, beds: 3, baths: 1, sqft: 1680 },
  { municipality: 'Whitemarsh', address: '19 Viburnum Ct', saleDate: '2026-07-01', salePrice: 560000, yearBuilt: 1991, beds: 3, baths: 2, halfBaths: 1, sqft: 1762 },
  { municipality: 'Whitemarsh', address: '101 Hampton Ln', saleDate: '2026-06-26', salePrice: 3200000, yearBuilt: 2015, beds: 4, baths: 4, halfBaths: 1, sqft: 5880 },
  { municipality: 'Whitemarsh', address: '473 Fort Hill Cir', saleDate: '2026-06-25', salePrice: 469900, yearBuilt: 2002, beds: 3, baths: 2, halfBaths: 1, sqft: 1768 },
  // --- Whitpain ------------------------------------------------------------------
  { municipality: 'Whitpain', address: '1070 Shepard Dr', saleDate: '2026-07-09', salePrice: 960000, yearBuilt: 1986, beds: 5, baths: 3, halfBaths: 1, sqft: 2748 },
  { municipality: 'Whitpain', address: '1420 Manor Ln', saleDate: '2026-07-01', salePrice: 810000, yearBuilt: 1957, beds: 4, baths: 3, halfBaths: 1, sqft: 2495 },
  { municipality: 'Whitpain', address: '450 Dundee Dr', saleDate: '2026-07-01', salePrice: 1100000, yearBuilt: 1981, beds: 4, baths: 2, halfBaths: 1, sqft: 3272 },
  { municipality: 'Whitpain', address: '13 Ramsgate Ct Unit 13', saleDate: '2026-06-30', salePrice: 485000, yearBuilt: 1980, beds: 3, baths: 2, halfBaths: 2, sqft: 1970 },
  { municipality: 'Whitpain', address: '1795 Skippack Pike', saleDate: '2026-06-30', salePrice: 500000, yearBuilt: 1930, beds: 4, baths: 1, halfBaths: 1, sqft: 1893 },
  // --- Worcester -----------------------------------------------------------------
  { municipality: 'Worcester', address: '116 Brindle Ct', saleDate: '2026-07-07', salePrice: 637750, yearBuilt: 2012, beds: 3, baths: 2, halfBaths: 2, sqft: 3356 },
  { municipality: 'Worcester', address: '2559 Crestline Dr', saleDate: '2026-06-26', salePrice: 895000, yearBuilt: 2003, beds: 4, baths: 2, halfBaths: 1, sqft: 3266 },
  { municipality: 'Worcester', address: '33 Tamarack Cir', saleDate: '2026-06-18', salePrice: 750000, yearBuilt: 2023, beds: 3, baths: 2, halfBaths: 2, sqft: 2678 },
  { municipality: 'Worcester', address: '1110 Arden Dr', saleDate: '2026-06-12', salePrice: 1232455, yearBuilt: 2026, beds: 4, baths: 3, halfBaths: 1, sqft: 3539 },
  { municipality: 'Worcester', address: '314 Silo Mill Ln', saleDate: '2026-06-11', salePrice: 650000, yearBuilt: 1997, beds: 3, baths: 2, halfBaths: 1, sqft: 3440 },
];

/**
Distinct municipalities represented in a list of sales, alphabetical. Shared
by municipalitiesWithSales/municipalitiesWithFreshSales below so the two
don't drift into different dedup/sort implementations.
*/
function uniqueMunicipalities(sales: RecentSale[]): string[] {
  return [...new Set(sales.map((s) => s.municipality))].toSorted((a, b) =>
    a.localeCompare(b),
  );
}

/**
Every municipality with at least one sale on file (fresh or stale), alphabetical.
*/
export function municipalitiesWithSales(): string[] {
  return uniqueMunicipalities(RECENT_SALES);
}

/**
Every municipality with at least one FRESH sale on file -- what the UI should
actually iterate over, since a town whose only records are stale has nothing
trustworthy to show.
*/
export function municipalitiesWithFreshSales(asOf: Date = new Date()): string[] {
  return uniqueMunicipalities(RECENT_SALES.filter((s) => !isSaleStale(s, asOf)));
}

/**
Whether a sale is too old to trust as market signal. See
docs/adr/0001-stale-data-threshold.md -- home sales go stale after 1 year.
*/
export function isSaleStale(sale: RecentSale, asOf: Date = new Date()): boolean {
  return isStale(sale.saleDate, 'homeSales', asOf);
}

/**
Every record on file, unfiltered -- includes stale sales. Use for audit/tests;
UI code should prefer `freshSalesIn`.
*/
export function salesIn(municipality: string): RecentSale[] {
  return RECENT_SALES.filter((s) => s.municipality === municipality);
}

/**
Sales on file that are still within the 1-year staleness threshold. This is
what `medianOf` and the UI should be called with -- a 1989 sale is not market
signal for a decision made today.
*/
export function freshSalesIn(municipality: string, asOf: Date = new Date()): RecentSale[] {
  return salesIn(municipality).filter((s) => !isSaleStale(s, asOf));
}

/**
Middle value of a town's sales on file -- explicitly NOT a statistical
median (see the file header). Named `medianOf` rather than `medianPriceFor`
so it can't be mistaken for the sourced `medianPrice` field in
`localMarket.ts` at a glance.
*/
export function medianOf(sales: RecentSale[]): number | null {
  if (sales.length === 0) return null;
  const sorted = sales.map((s) => s.salePrice).toSorted((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
}
